server:
  address: ":3290"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  dumpRouterMap: true
  routeOverWrite: true
  accessLogEnabled: true

project:
  platform: "docker"
  language: "zh-CN"

logger:
  path: "resource/log/system/"
  prefix: ""
  file: "{Y-m-d}.log"
  level: "all"
  stdout: true

# Database.
database:
  logger:
    level: "all"
    stdout: true
    Path: "resource/log/sql"

