services:
  live-dog:
    container_name: live-dog
    image: shichen437/live-dog:latest
    restart: always
    ports:
      - '9876:9876'
    volumes:
      - /Users/shichen/Downloads/upload:/LiveDog/upload
      - /Users/shichen/Downloads/output:/LiveDog/video
    environment:
      - DATABASE_DEFAULT_LINK=mysql:root:123456@tcp(192.168.3.16:13306)/live-dog-copy?charset=utf8mb4&parseTime=true&loc=Local
