// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/shichen437/live-dog/internal/app/live/dao/internal"
)

// internalAuthorInfoHistoryDao is internal type for wrapping internal DAO implements.
type internalAuthorInfoHistoryDao = *internal.AuthorInfoHistoryDao

// authorInfoHistoryDao is the data access object for table author_info_history.
// You can define custom methods on it to extend its functionality as you wish.
type authorInfoHistoryDao struct {
	internalAuthorInfoHistoryDao
}

var (
	// AuthorInfoHistory is globally public accessible object for table author_info_history operations.
	AuthorInfoHistory = authorInfoHistoryDao{
		internal.NewAuthorInfoHistoryDao(),
	}
)

// Fill with you ideas below.
