// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/shichen437/live-dog/internal/app/live/dao/internal"
)

// internalDownloadRecordDao is internal type for wrapping internal DAO implements.
type internalDownloadRecordDao = *internal.DownloadRecordDao

// downloadRecordDao is the data access object for table download_record.
// You can define custom methods on it to extend its functionality as you wish.
type downloadRecordDao struct {
	internalDownloadRecordDao
}

var (
	// DownloadRecord is globally public accessible object for table download_record operations.
	DownloadRecord = downloadRecordDao{
		internal.NewDownloadRecordDao(),
	}
)

// Fill with you ideas below.
